name: test-orders

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && npm install && npm run test:ci
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
